# Site settings
title: Your awesome title
description: HI THERE
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
sass:
  sass_dir: _sass
  style: compressed